zynqmp: Fix coord driver compilation error
Fix coord driver compilation on newer kernels:

drivers/xen/coord_suspend.c:97:34: error: array type has incomplete element type ‘struct of_device_id’
 static const struct of_device_id coord_susp_of_match[] = {

This is due to:
ac3167257b9f ("headers: separate linux/mod_devicetable.h from linux/platform_device.h")

Signed-off-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>